#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.15
# from Racc grammer file "".
#

require 'racc/parser.rb'


# Clases requeridas
require_relative 'lexer'
require_relative 'clasesGusb'
require_relative 'clasesContexto'

# Errores sintacticos
class ErrorSintactico < RuntimeError

	def initialize(token)
		@token = token
	end

	def to_s
		"ERROR: fila: " + @token.fila.to_s() + ", columna: " + @token.columna.to_s() + ", token inesperado: #{@token.token} \n"  
	end
end

# Main del Parser
class ParserGusb < Racc::Parser

module_eval(<<'...end parserGusb2.y/module_eval...', 'parserGusb2.y', 239)
	
	def initialize(tokens)
		@tokens = tokens
		@yydebug = true
		super()
	end 

	def parse
		do_parse
	end

	def next_token
		@tokens.shift
	end

	def on_error(id, token, pila)
		raise ErrorSintactico.new(token)
	end
...end parserGusb2.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
     9,    91,    92,    14,    16,    93,    60,    21,    93,    19,
    20,    18,     9,    29,    30,    14,    16,    17,    29,    21,
    29,    19,    20,    18,     9,    29,    61,    14,    16,    17,
     5,    21,    60,    19,    20,    18,    55,    44,     9,    66,
   139,    17,   139,   100,   101,   102,    67,   139,    89,     6,
   131,     9,   129,    45,    46,    94,    64,     9,    70,    39,
    69,     6,    44,    23,    40,    22,     3,    55,    44,     9,
    41,   148,   149,     6,    55,    44,     9,   100,   101,   102,
    34,    35,    37,    36,    45,    46,   100,   101,   102,     2,
    39,    45,    46,     9,     9,    40,    68,    39,    74,    73,
    75,    41,    40,    74,    73,    75,    44,     9,    41,    44,
    66,    34,    35,    37,    36,    44,     9,   130,    34,    35,
    37,    36,    45,    46,   100,   101,   102,   157,    39,   158,
     9,    45,    46,    40,    29,   161,   162,    39,   nil,    41,
    44,     9,    40,   nil,   nil,   nil,   nil,   nil,    41,    34,
    35,    37,    36,   nil,    44,     9,    45,    46,    34,    35,
    37,    36,    39,   nil,   nil,   nil,   nil,    40,   nil,   nil,
    45,    46,   nil,    41,    44,     9,    39,   nil,   nil,   nil,
   nil,    40,   nil,    34,    35,    37,    36,    41,    44,     9,
    45,    46,   nil,   nil,   nil,   nil,    39,    34,    35,    37,
    36,    40,   nil,   nil,    45,    46,   nil,    41,    44,     9,
    39,   nil,   nil,   nil,   nil,    40,   nil,    34,    35,    37,
    36,    41,   nil,   nil,    45,    46,   nil,   nil,   nil,   nil,
    39,    34,    35,    37,    36,    40,    71,    79,   nil,     9,
   nil,    41,    14,    16,   nil,   nil,    21,   nil,    19,    20,
    18,    34,    35,    37,    36,    76,    17,    44,     9,   nil,
   nil,    72,    74,    73,    75,    78,    77,   nil,    81,    82,
    83,    84,    80,    45,    46,   nil,   nil,    44,     9,    39,
   nil,   nil,   141,   nil,    40,   nil,   nil,   nil,   nil,   nil,
    41,    44,     9,    45,    46,   nil,   nil,   nil,   nil,    39,
    34,    35,    37,    36,    40,   nil,   nil,    45,    46,   nil,
    41,    44,     9,    39,   nil,   nil,   nil,   nil,    40,   nil,
    34,    35,    37,    36,    41,    44,     9,    45,    46,   nil,
   nil,   nil,   nil,    39,    34,    35,    37,    36,    40,   nil,
   nil,    45,    46,   nil,    41,    44,     9,    39,   nil,   nil,
   nil,   nil,    40,   nil,    34,    35,    37,    36,    41,    44,
     9,    45,    46,   nil,   nil,   nil,   nil,    39,    34,    35,
    37,    36,    40,   nil,   nil,    45,    46,   nil,    41,    44,
     9,    39,   nil,   nil,   nil,   nil,    40,   nil,    34,    35,
    37,    36,    41,    44,     9,    45,    46,   nil,   nil,   nil,
   nil,    39,    34,    35,    37,    36,    40,   nil,   nil,    45,
    46,   nil,    41,    44,     9,    39,   nil,   nil,   nil,   nil,
    40,   nil,    34,    35,    37,    36,    41,    44,     9,    45,
    46,   nil,   nil,   nil,   nil,    39,    34,    35,    37,    36,
    40,   nil,   nil,    45,    46,   nil,    41,    44,     9,    39,
   nil,   nil,   nil,   nil,    40,   nil,    34,    35,    37,    36,
    41,    44,     9,    45,    46,   nil,   nil,   nil,   nil,    39,
    34,    35,    37,    36,    40,   nil,   nil,    45,    46,   nil,
    41,    44,     9,    39,   nil,   nil,   nil,   nil,    40,   nil,
    34,    35,    37,    36,    41,    44,     9,    45,    46,   nil,
   nil,   nil,   nil,    39,    34,    35,    37,    36,    40,   nil,
   nil,    45,    46,   nil,    41,    44,     9,    39,   nil,   nil,
   nil,   nil,    40,   nil,    34,    35,    37,    36,    41,    44,
     9,    45,    46,   nil,   nil,   nil,   nil,    39,    34,    35,
    37,    36,    40,   nil,   nil,    45,    46,   nil,    41,    44,
     9,    39,   nil,   nil,   nil,   nil,    40,   nil,    34,    35,
    37,    36,    41,    44,     9,    45,    46,   nil,   nil,   nil,
   nil,    39,    34,    35,    37,    36,    40,   nil,   nil,    45,
    46,   nil,    41,    44,     9,    39,   nil,   nil,   nil,   nil,
    40,   nil,    34,    35,    37,    36,    41,    44,     9,    45,
    46,   nil,   nil,   nil,   nil,    39,    34,    35,    37,    36,
    40,   nil,   nil,    45,    46,   nil,    41,    44,     9,    39,
   nil,   nil,   nil,   nil,    40,   nil,    34,    35,    37,    36,
    41,    44,     9,    45,    46,   nil,   nil,   nil,   nil,    39,
    34,    35,    37,    36,    40,   nil,   nil,    45,    46,   nil,
    41,   nil,   nil,    39,    71,    79,   nil,   nil,    40,   nil,
    34,    35,    37,    36,    41,   nil,   nil,   nil,   nil,    71,
   -75,   nil,   nil,    76,    34,    35,    37,    36,   nil,    72,
    74,    73,    75,    78,    77,   nil,    81,    82,    83,    84,
    80,    71,    79,   133,    72,    74,    73,    75,   nil,   nil,
   nil,    81,    82,    83,    84,   -75,   nil,   nil,   nil,   nil,
    76,    71,    79,   nil,   nil,   nil,    72,    74,    73,    75,
    78,    77,   nil,    81,    82,    83,    84,    80,   nil,   132,
    76,   nil,   150,    71,    79,   nil,    72,    74,    73,    75,
    78,    77,   nil,    81,    82,    83,    84,    80,   nil,   nil,
   nil,   nil,    76,    71,    79,   nil,   nil,   nil,    72,    74,
    73,    75,    78,    77,   nil,    81,    82,    83,    84,    80,
    71,   -75,    76,   nil,   nil,   nil,   nil,   nil,    72,    74,
    73,    75,    78,    77,   nil,    81,    82,    83,    84,    80,
    71,    79,   nil,   nil,   nil,    72,    74,    73,    75,   nil,
   nil,   nil,    81,    82,    83,    84,   -75,    71,    79,    76,
   nil,   nil,   nil,   nil,   nil,    72,    74,    73,    75,    78,
    77,   nil,    81,    82,    83,    84,    80,    71,    79,   nil,
   nil,   nil,    72,    74,    73,    75,   nil,    77,   nil,    81,
    82,    83,    84,    80,   nil,   nil,    76,    71,    79,   nil,
   nil,   151,    72,    74,    73,    75,    78,    77,   nil,    81,
    82,    83,    84,    80,    71,    79,    76,   nil,   nil,   nil,
   nil,    90,    72,    74,    73,    75,    78,    77,   nil,    81,
    82,    83,    84,    80,    71,    79,   nil,   nil,   nil,    72,
    74,    73,    75,    78,    77,   nil,    81,    82,    83,    84,
    80,   nil,   nil,    76,    71,    79,   nil,   nil,    85,    72,
    74,    73,    75,    78,    77,   nil,    81,    82,    83,    84,
    80,   nil,   nil,    76,   nil,   137,    71,    79,   nil,    72,
    74,    73,    75,    78,    77,   nil,    81,    82,    83,    84,
    80,   nil,   nil,   nil,   nil,    76,   nil,   136,    71,    79,
   nil,    72,    74,    73,    75,    78,    77,   nil,    81,    82,
    83,    84,    80,   nil,   nil,   nil,   nil,    76,   nil,   135,
    71,    79,   nil,    72,    74,    73,    75,    78,    77,   nil,
    81,    82,    83,    84,    80,   nil,   nil,   nil,   nil,    76,
   nil,   134,    71,    79,   nil,    72,    74,    73,    75,    78,
    77,   nil,    81,    82,    83,    84,    80,    71,    79,   nil,
   nil,    76,   nil,   nil,   nil,   nil,   152,    72,    74,    73,
    75,    78,    77,   nil,    81,    82,    83,    84,    80,    71,
    79,   nil,    72,    74,    73,    75,   nil,   nil,   nil,    81,
    82,    83,    84,    80,    71,   nil,   nil,   nil,    76,   nil,
   124,   nil,   nil,   nil,    72,    74,    73,    75,    78,    77,
    71,    81,    82,    83,    84,    80,   nil,   nil,   nil,    72,
    74,    73,    75,    71,   nil,   nil,   -75,   -75,   -75,   -75,
   nil,   nil,   nil,   nil,    71,    72,    74,    73,    75,   nil,
   nil,   nil,   -75,   -75,   -75,   -75,   nil,   nil,    72,    74,
    73,    75,   nil,   nil,   nil,   -75,   -75,   -75,   -75,    72,
    74,    73,    75,   nil,   nil,   nil,   -75,   -75,   -75,   -75,
     9,   nil,   nil,    14,    16,   nil,   nil,    21,   nil,    19,
    20,    18,     9,   nil,   nil,    14,    16,    17,   nil,    21,
   nil,    19,    20,    18,    59,   nil,   nil,     9,   nil,    17,
    14,    16,   nil,   nil,    21,   nil,    19,    20,    18,     9,
   nil,   nil,    14,    16,    17,   nil,    21,   nil,    19,    20,
    18,   nil,   nil,   nil,   nil,   nil,    17 ]

racc_action_check = [
    17,    49,    50,    17,    17,    53,    28,    17,    56,    17,
    17,    17,     2,     7,     8,     2,     2,    17,   156,     2,
   123,     2,     2,     2,   157,   125,    28,   157,   157,     2,
     2,   157,    96,   157,   157,   157,    19,    19,    19,    32,
   156,   157,   123,   148,   148,   148,    34,   125,    47,    17,
   102,    18,    96,    19,    19,    57,    32,     6,    37,    19,
    36,     2,   131,     4,    19,     3,     1,    93,    93,    93,
    19,   142,   144,   157,    20,    20,    20,   130,   130,   130,
    19,    19,    19,    19,    93,    93,   129,   129,   129,     0,
    93,    20,    20,    60,    59,    93,    35,    20,   109,   109,
   109,    93,    20,   110,   110,   110,    94,    94,    20,   149,
   150,    93,    93,    93,    93,   133,   133,    97,    20,    20,
    20,    20,    94,    94,    61,    61,    61,   152,    94,   154,
    21,   133,   133,    94,    58,   160,   161,   133,   nil,    94,
    14,    14,   133,   nil,   nil,   nil,   nil,   nil,   133,    94,
    94,    94,    94,   nil,    16,    16,    14,    14,   133,   133,
   133,   133,    14,   nil,   nil,   nil,   nil,    14,   nil,   nil,
    16,    16,   nil,    14,   139,   139,    16,   nil,   nil,   nil,
   nil,    16,   nil,    14,    14,    14,    14,    16,    84,    84,
   139,   139,   nil,   nil,   nil,   nil,   139,    16,    16,    16,
    16,   139,   nil,   nil,    84,    84,   nil,   139,   141,   141,
    84,   nil,   nil,   nil,   nil,    84,   nil,   139,   139,   139,
   139,    84,   nil,   nil,   141,   141,   nil,   nil,   nil,   nil,
   141,    84,    84,    84,    84,   141,   128,   128,   nil,    85,
   nil,   141,    85,    85,   nil,   nil,    85,   nil,    85,    85,
    85,   141,   141,   141,   141,   128,    85,    83,    83,   nil,
   nil,   128,   128,   128,   128,   128,   128,   nil,   128,   128,
   128,   128,   128,    83,    83,   nil,   nil,    82,    82,    83,
   nil,   nil,   128,   nil,    83,   nil,   nil,   nil,   nil,   nil,
    83,    81,    81,    82,    82,   nil,   nil,   nil,   nil,    82,
    83,    83,    83,    83,    82,   nil,   nil,    81,    81,   nil,
    82,    80,    80,    81,   nil,   nil,   nil,   nil,    81,   nil,
    82,    82,    82,    82,    81,    30,    30,    80,    80,   nil,
   nil,   nil,   nil,    80,    81,    81,    81,    81,    80,   nil,
   nil,    30,    30,   nil,    80,    78,    78,    30,   nil,   nil,
   nil,   nil,    30,   nil,    80,    80,    80,    80,    30,    77,
    77,    78,    78,   nil,   nil,   nil,   nil,    78,    30,    30,
    30,    30,    78,   nil,   nil,    77,    77,   nil,    78,    76,
    76,    77,   nil,   nil,   nil,   nil,    77,   nil,    78,    78,
    78,    78,    77,    75,    75,    76,    76,   nil,   nil,   nil,
   nil,    76,    77,    77,    77,    77,    76,   nil,   nil,    75,
    75,   nil,    76,    74,    74,    75,   nil,   nil,   nil,   nil,
    75,   nil,    76,    76,    76,    76,    75,    73,    73,    74,
    74,   nil,   nil,   nil,   nil,    74,    75,    75,    75,    75,
    74,   nil,   nil,    73,    73,   nil,    74,    39,    39,    73,
   nil,   nil,   nil,   nil,    73,   nil,    74,    74,    74,    74,
    73,    40,    40,    39,    39,   nil,   nil,   nil,   nil,    39,
    73,    73,    73,    73,    39,   nil,   nil,    40,    40,   nil,
    39,    41,    41,    40,   nil,   nil,   nil,   nil,    40,   nil,
    39,    39,    39,    39,    40,    72,    72,    41,    41,   nil,
   nil,   nil,   nil,    41,    40,    40,    40,    40,    41,   nil,
   nil,    72,    72,   nil,    41,    71,    71,    72,   nil,   nil,
   nil,   nil,    72,   nil,    41,    41,    41,    41,    72,    70,
    70,    71,    71,   nil,   nil,   nil,   nil,    71,    72,    72,
    72,    72,    71,   nil,   nil,    70,    70,   nil,    71,    69,
    69,    70,   nil,   nil,   nil,   nil,    70,   nil,    71,    71,
    71,    71,    70,    68,    68,    69,    69,   nil,   nil,   nil,
   nil,    69,    70,    70,    70,    70,    69,   nil,   nil,    68,
    68,   nil,    69,    67,    67,    68,   nil,   nil,   nil,   nil,
    68,   nil,    69,    69,    69,    69,    68,    66,    66,    67,
    67,   nil,   nil,   nil,   nil,    67,    68,    68,    68,    68,
    67,   nil,   nil,    66,    66,   nil,    67,    64,    64,    66,
   nil,   nil,   nil,   nil,    66,   nil,    67,    67,    67,    67,
    66,    79,    79,    64,    64,   nil,   nil,   nil,   nil,    64,
    66,    66,    66,    66,    64,   nil,   nil,    79,    79,   nil,
    64,   nil,   nil,    79,   104,   104,   nil,   nil,    79,   nil,
    64,    64,    64,    64,    79,   nil,   nil,   nil,   nil,   118,
   118,   nil,   nil,   104,    79,    79,    79,    79,   nil,   104,
   104,   104,   104,   104,   104,   nil,   104,   104,   104,   104,
   104,   103,   103,   104,   118,   118,   118,   118,   nil,   nil,
   nil,   118,   118,   118,   118,   118,   nil,   nil,   nil,   nil,
   103,   145,   145,   nil,   nil,   nil,   103,   103,   103,   103,
   103,   103,   nil,   103,   103,   103,   103,   103,   nil,   103,
   145,   nil,   145,    63,    63,   nil,   145,   145,   145,   145,
   145,   145,   nil,   145,   145,   145,   145,   145,   nil,   nil,
   nil,   nil,    63,   126,   126,   nil,   nil,   nil,    63,    63,
    63,    63,    63,    63,   nil,    63,    63,    63,    63,    63,
   117,   117,   126,   nil,   nil,   nil,   nil,   nil,   126,   126,
   126,   126,   126,   126,   nil,   126,   126,   126,   126,   126,
    52,    52,   nil,   nil,   nil,   117,   117,   117,   117,   nil,
   nil,   nil,   117,   117,   117,   117,   117,   116,   116,    52,
   nil,   nil,   nil,   nil,   nil,    52,    52,    52,    52,    52,
    52,   nil,    52,    52,    52,    52,    52,   146,   146,   nil,
   nil,   nil,   116,   116,   116,   116,   nil,   116,   nil,   116,
   116,   116,   116,   116,   nil,   nil,   146,    48,    48,   nil,
   nil,   146,   146,   146,   146,   146,   146,   146,   nil,   146,
   146,   146,   146,   146,   114,   114,    48,   nil,   nil,   nil,
   nil,    48,    48,    48,    48,    48,    48,    48,   nil,    48,
    48,    48,    48,    48,    38,    38,   nil,   nil,   nil,   114,
   114,   114,   114,   114,   114,   nil,   114,   114,   114,   114,
   114,   nil,   nil,    38,   108,   108,   nil,   nil,    38,    38,
    38,    38,    38,    38,    38,   nil,    38,    38,    38,    38,
    38,   nil,   nil,   108,   nil,   108,   107,   107,   nil,   108,
   108,   108,   108,   108,   108,   nil,   108,   108,   108,   108,
   108,   nil,   nil,   nil,   nil,   107,   nil,   107,   106,   106,
   nil,   107,   107,   107,   107,   107,   107,   nil,   107,   107,
   107,   107,   107,   nil,   nil,   nil,   nil,   106,   nil,   106,
   105,   105,   nil,   106,   106,   106,   106,   106,   106,   nil,
   106,   106,   106,   106,   106,   nil,   nil,   nil,   nil,   105,
   nil,   105,   147,   147,   nil,   105,   105,   105,   105,   105,
   105,   nil,   105,   105,   105,   105,   105,   115,   115,   nil,
   nil,   147,   nil,   nil,   nil,   nil,   147,   147,   147,   147,
   147,   147,   147,   nil,   147,   147,   147,   147,   147,    86,
    86,   nil,   115,   115,   115,   115,   nil,   nil,   nil,   115,
   115,   115,   115,   115,   120,   nil,   nil,   nil,    86,   nil,
    86,   nil,   nil,   nil,    86,    86,    86,    86,    86,    86,
   121,    86,    86,    86,    86,    86,   nil,   nil,   nil,   120,
   120,   120,   120,   122,   nil,   nil,   120,   120,   120,   120,
   nil,   nil,   nil,   nil,   119,   121,   121,   121,   121,   nil,
   nil,   nil,   121,   121,   121,   121,   nil,   nil,   122,   122,
   122,   122,   nil,   nil,   nil,   122,   122,   122,   122,   119,
   119,   119,   119,   nil,   nil,   nil,   119,   119,   119,   119,
    24,   nil,   nil,    24,    24,   nil,   nil,    24,   nil,    24,
    24,    24,   151,   nil,   nil,   151,   151,    24,   nil,   151,
   nil,   151,   151,   151,    24,   nil,   nil,    29,   nil,   151,
    29,    29,   nil,   nil,    29,   nil,    29,    29,    29,    90,
   nil,   nil,    90,    90,    29,   nil,    90,   nil,    90,    90,
    90,   nil,   nil,   nil,   nil,   nil,    90 ]

racc_action_pointer = [
    68,    66,     8,    65,    41,   nil,    53,   -15,   -13,   nil,
   nil,   nil,   nil,   nil,   137,   nil,   151,    -4,    47,    34,
    72,   126,   nil,   nil,  1116,   nil,   nil,   nil,   -18,  1143,
   322,   nil,    14,   nil,    21,    71,    35,    33,   879,   444,
   458,   478,   nil,   nil,   nil,   nil,   nil,    38,   842,    -8,
   -20,   nil,   785,   -40,   nil,   nil,   -37,     3,   106,    90,
    89,   108,   nil,   728,   614,   nil,   594,   580,   560,   546,
   526,   512,   492,   424,   410,   390,   376,   356,   342,   628,
   308,   288,   274,   254,   185,   235,  1024,   nil,   nil,   nil,
  1155,   nil,   nil,    65,   103,   nil,     8,    93,   nil,   nil,
   nil,   nil,     8,   686,   649,   965,   943,   921,   899,    67,
    72,   nil,   nil,   nil,   859,  1002,   802,   765,   664,  1079,
  1039,  1055,  1068,    -8,   nil,    -3,   748,   nil,   231,    70,
    61,    59,   nil,   112,   nil,   nil,   nil,   nil,   nil,   171,
   nil,   205,    47,   nil,    49,   706,   822,   987,    27,   106,
    85,  1128,   106,   nil,    86,   nil,   -10,    20,   nil,   nil,
   113,   124,   nil ]

racc_action_default = [
   -75,   -75,   -75,   -75,   -75,    -2,   -75,    -4,   -75,   -17,
   -52,   -53,   -54,   -55,   -75,   -57,   -75,   -75,   -75,   -75,
   -75,   -75,   163,    -1,   -75,    -5,    -7,    -8,   -75,   -75,
   -75,   -18,   -19,   -20,   -75,   -75,   -75,   -75,   -75,   -75,
   -75,   -75,   -42,   -43,   -48,   -49,   -50,   -75,   -75,   -75,
   -75,   -60,   -63,   -61,   -64,   -67,   -62,   -75,    -3,   -75,
   -75,   -75,   -51,   -16,   -75,   -45,   -75,   -75,   -75,   -75,
   -75,   -75,   -75,   -75,   -75,   -75,   -75,   -75,   -75,   -75,
   -75,   -75,   -75,   -75,   -75,   -75,   -75,   -32,   -37,   -56,
   -75,   -58,   -59,   -75,   -75,    -6,   -75,   -75,   -12,   -11,
   -13,   -14,   -75,   -75,   -75,   -75,   -75,   -75,   -75,   -25,
   -26,   -27,   -28,   -29,   -30,   -33,   -34,   -35,   -36,   -38,
   -39,   -40,   -41,   -69,   -31,   -73,   -65,   -66,   -75,   -75,
   -75,   -75,   -44,   -75,   -21,   -22,   -23,   -24,   -68,   -75,
   -74,   -75,   -11,    -9,   -75,   -75,   -75,   -75,   -75,   -75,
   -47,   -75,   -75,   -10,   -75,   -46,   -71,   -75,   -15,   -70,
   -75,   -75,   -72 ]

racc_goto_table = [
     4,     8,    58,    65,    99,    28,   138,    25,   140,   144,
    53,    56,    24,    62,    47,    50,     8,    51,    49,    97,
    57,    98,   127,     8,     1,   nil,   nil,   154,     8,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   159,
    38,   nil,    48,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    63,   nil,    28,    96,
    95,   nil,   nil,   123,   nil,    86,    87,    88,   125,   nil,
   nil,   nil,   142,   143,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     8,   nil,   nil,   nil,   nil,     8,
   103,   153,   104,   105,   106,   107,   108,   109,   110,   111,
   112,   113,   114,   115,   116,   117,   118,   119,   120,   121,
   122,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   126,
   128,   155,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   156,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     8,   nil,   nil,   nil,   nil,   160,     8,   nil,   nil,   145,
   nil,   nil,   nil,   nil,   nil,   146,   nil,   147 ]

racc_goto_check = [
     2,     8,     4,    16,     9,     8,    25,     5,    25,    10,
    23,    23,     3,    17,    20,     2,     8,     8,    22,     6,
     8,     7,    24,     8,     1,   nil,   nil,    10,     8,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    25,
    12,   nil,    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    12,   nil,     8,     8,
     5,   nil,   nil,     4,   nil,    12,    12,    12,     4,   nil,
   nil,   nil,     9,     9,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     8,   nil,   nil,   nil,   nil,     8,
    12,     9,    12,    12,    12,    12,    12,    12,    12,    12,
    12,    12,    12,    12,    12,    12,    12,    12,    12,    12,
    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    12,
    12,    16,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     4,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     8,   nil,   nil,   nil,   nil,     2,     8,   nil,   nil,    12,
   nil,   nil,   nil,   nil,   nil,    12,   nil,    12 ]

racc_goto_pointer = [
   nil,    24,    -2,     6,   -22,     1,   -41,   -39,    -1,   -57,
  -122,   nil,    26,   nil,   nil,   nil,   -29,   -16,   nil,   nil,
     0,   nil,     2,    -9,   -71,  -117 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,     7,   nil,    26,    27,    32,   nil,
    42,    11,    52,    31,    33,    43,   nil,    10,    12,    13,
   nil,    15,   nil,   nil,    54,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 57, :_reduce_1,
  2, 57, :_reduce_2,
  3, 58, :_reduce_3,
  1, 58, :_reduce_4,
  1, 59, :_reduce_5,
  3, 59, :_reduce_6,
  1, 61, :_reduce_7,
  1, 61, :_reduce_8,
  5, 62, :_reduce_9,
  7, 62, :_reduce_10,
  3, 63, :_reduce_11,
  3, 63, :_reduce_12,
  1, 65, :_reduce_13,
  1, 65, :_reduce_14,
  6, 65, :_reduce_15,
  3, 67, :_reduce_16,
  1, 64, :_reduce_17,
  1, 68, :_reduce_18,
  1, 68, :_reduce_19,
  1, 68, :_reduce_20,
  4, 68, :_reduce_21,
  4, 68, :_reduce_22,
  4, 68, :_reduce_23,
  4, 68, :_reduce_24,
  3, 68, :_reduce_25,
  3, 68, :_reduce_26,
  3, 68, :_reduce_27,
  3, 68, :_reduce_28,
  3, 68, :_reduce_29,
  3, 68, :_reduce_30,
  3, 68, :_reduce_31,
  2, 68, :_reduce_32,
  3, 68, :_reduce_33,
  3, 68, :_reduce_34,
  3, 68, :_reduce_35,
  3, 68, :_reduce_36,
  2, 68, :_reduce_37,
  3, 68, :_reduce_38,
  3, 68, :_reduce_39,
  3, 68, :_reduce_40,
  3, 68, :_reduce_41,
  1, 69, :_reduce_none,
  1, 69, :_reduce_none,
  4, 70, :_reduce_44,
  2, 70, :_reduce_45,
  6, 72, :_reduce_46,
  5, 72, :_reduce_47,
  1, 66, :_reduce_48,
  1, 71, :_reduce_49,
  1, 71, :_reduce_50,
  3, 60, :_reduce_51,
  1, 60, :_reduce_52,
  1, 73, :_reduce_53,
  1, 73, :_reduce_54,
  1, 73, :_reduce_55,
  3, 73, :_reduce_56,
  1, 73, :_reduce_57,
  3, 73, :_reduce_58,
  3, 73, :_reduce_59,
  2, 74, :_reduce_60,
  2, 75, :_reduce_61,
  2, 75, :_reduce_62,
  1, 79, :_reduce_63,
  1, 79, :_reduce_64,
  3, 79, :_reduce_65,
  3, 79, :_reduce_66,
  1, 80, :_reduce_67,
  4, 76, :_reduce_68,
  3, 76, :_reduce_69,
  5, 81, :_reduce_70,
  4, 81, :_reduce_71,
  11, 77, :_reduce_72,
  3, 78, :_reduce_73,
  4, 78, :_reduce_74 ]

racc_reduce_n = 75

racc_shift_n = 163

racc_token_table = {
  false => 0,
  :error => 1,
  "TkString" => 2,
  "TkNum" => 3,
  "TkId" => 4,
  "TkPlus" => 5,
  "TkEqual" => 6,
  "TkIf" => 7,
  "TkDo" => 8,
  "TkOd" => 9,
  "TkFi" => 10,
  "TkFor" => 11,
  "TkRof" => 12,
  "TkPrint" => 13,
  "TkPrintln" => 14,
  "TkRead" => 15,
  "Tkint" => 16,
  "Tkbool" => 17,
  "Tkarray" => 18,
  "TkTrue" => 19,
  "TkFalse" => 20,
  "Tk0Block" => 21,
  "TkCBlock" => 22,
  "TkSoForth" => 23,
  "TkComma" => 24,
  "TkOpenPar" => 25,
  "TkClosePar" => 26,
  "TkAsig" => 27,
  "TkSemicolon" => 28,
  "TkArrow" => 29,
  "TkMinus" => 30,
  "TkDiv" => 31,
  "TkMult" => 32,
  "TkMod" => 33,
  "TkOr" => 34,
  "TkAnd" => 35,
  "TkNot" => 36,
  "TkLess" => 37,
  "TkLeq" => 38,
  "TkGeq" => 39,
  "TkGreater" => 40,
  "TkNEqual" => 41,
  "Tk0Bracket" => 42,
  "TkCBracket" => 43,
  "TkTwoPoints" => 44,
  "TkConcat" => 45,
  "TkAtoi" => 46,
  "TkSize" => 47,
  "TkMax" => 48,
  "TkMin" => 49,
  "TkGuard" => 50,
  "Tkto" => 51,
  "Tkin" => 52,
  "TkDeclare" => 53,
  :right => 54,
  :UMINUS => 55 }

racc_nt_base = 56

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"TkString\"",
  "\"TkNum\"",
  "\"TkId\"",
  "\"TkPlus\"",
  "\"TkEqual\"",
  "\"TkIf\"",
  "\"TkDo\"",
  "\"TkOd\"",
  "\"TkFi\"",
  "\"TkFor\"",
  "\"TkRof\"",
  "\"TkPrint\"",
  "\"TkPrintln\"",
  "\"TkRead\"",
  "\"Tkint\"",
  "\"Tkbool\"",
  "\"Tkarray\"",
  "\"TkTrue\"",
  "\"TkFalse\"",
  "\"Tk0Block\"",
  "\"TkCBlock\"",
  "\"TkSoForth\"",
  "\"TkComma\"",
  "\"TkOpenPar\"",
  "\"TkClosePar\"",
  "\"TkAsig\"",
  "\"TkSemicolon\"",
  "\"TkArrow\"",
  "\"TkMinus\"",
  "\"TkDiv\"",
  "\"TkMult\"",
  "\"TkMod\"",
  "\"TkOr\"",
  "\"TkAnd\"",
  "\"TkNot\"",
  "\"TkLess\"",
  "\"TkLeq\"",
  "\"TkGeq\"",
  "\"TkGreater\"",
  "\"TkNEqual\"",
  "\"Tk0Bracket\"",
  "\"TkCBracket\"",
  "\"TkTwoPoints\"",
  "\"TkConcat\"",
  "\"TkAtoi\"",
  "\"TkSize\"",
  "\"TkMax\"",
  "\"TkMin\"",
  "\"TkGuard\"",
  "\"Tkto\"",
  "\"Tkin\"",
  "\"TkDeclare\"",
  "right",
  "UMINUS",
  "$start",
  "PROGRAMA",
  "CUERPO",
  "LISTA_DECLARACION",
  "INSTRUCCIONES",
  "DECLARACION",
  "DECLA_CARD",
  "DECLA_TIPO",
  "IDENTIFICADOR",
  "TIPO",
  "LITERAL_NUMERO",
  "ASIGNACION",
  "EXPRESION",
  "LITERAL",
  "EXP_ARRAY",
  "LITERAL_BOOLEANO",
  "EXP_ARRAY_REC",
  "INSTRUCCION",
  "ENTRADA",
  "SALIDA",
  "CONDICIONAL",
  "ITERACION_FOR",
  "ITERACION_DO",
  "IMPRIMIR",
  "STRING",
  "GUARDIA" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'parserGusb2.y', 44)
  def _reduce_1(val, _values, result)
     result = Programa.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 45)
  def _reduce_2(val, _values, result)
     result = Programa.new(nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 50)
  def _reduce_3(val, _values, result)
     result = Cuerpo.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 51)
  def _reduce_4(val, _values, result)
     result = Cuerpo.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 56)
  def _reduce_5(val, _values, result)
     result = ListaDeclaracion.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 57)
  def _reduce_6(val, _values, result)
     result = ListaDeclaracion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 62)
  def _reduce_7(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 63)
  def _reduce_8(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 66)
  def _reduce_9(val, _values, result)
    result = Decla_Card.new(val[0],nil,val[4],nil,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 67)
  def _reduce_10(val, _values, result)
    result = Decla_Card.new(val[0],val[2],val[4],val[6],nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 70)
  def _reduce_11(val, _values, result)
    result = Decla_Tipo.new(val[0],nil,val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 71)
  def _reduce_12(val, _values, result)
    result = Decla_Tipo.new(val[0],val[2],nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 77)
  def _reduce_13(val, _values, result)
     result = TipoNum.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 78)
  def _reduce_14(val, _values, result)
     result = TipoBool.new(val[0])  
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 79)
  def _reduce_15(val, _values, result)
     result = TipoArray.new(val[0],val[2],val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 84)
  def _reduce_16(val, _values, result)
     result = Asignacion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 95)
  def _reduce_17(val, _values, result)
     result = Identificador.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 100)
  def _reduce_18(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 101)
  def _reduce_19(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 102)
  def _reduce_20(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 103)
  def _reduce_21(val, _values, result)
     result = Atoi.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 104)
  def _reduce_22(val, _values, result)
     result = Size.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 105)
  def _reduce_23(val, _values, result)
     result = Min.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 106)
  def _reduce_24(val, _values, result)
     result = Max.new(val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 107)
  def _reduce_25(val, _values, result)
    result = OpSuma.new(val[0],val[1],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 108)
  def _reduce_26(val, _values, result)
     result = OpResta.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 109)
  def _reduce_27(val, _values, result)
     result = OpMultiplicacion.new(val[0],val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 110)
  def _reduce_28(val, _values, result)
     result = OpDivisionE.new(val[0],val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 111)
  def _reduce_29(val, _values, result)
     result = OpModE.new(val[0],val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 112)
  def _reduce_30(val, _values, result)
     result = OpComa.new(val[0],val[1],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 113)
  def _reduce_31(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 114)
  def _reduce_32(val, _values, result)
     result = OpUMINUS.new(val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 115)
  def _reduce_33(val, _values, result)
     result = OpAnd.new(val[0],val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 116)
  def _reduce_34(val, _values, result)
     result = OpOr.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 117)
  def _reduce_35(val, _values, result)
     result = OpEquivalente.new(val[0],val[1],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 118)
  def _reduce_36(val, _values, result)
     result = OpDesigual.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 119)
  def _reduce_37(val, _values, result)
     result = OpExclamacion.new(val[0],val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 120)
  def _reduce_38(val, _values, result)
     result = OpMenor.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 121)
  def _reduce_39(val, _values, result)
     result = OpMenorIgual.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 122)
  def _reduce_40(val, _values, result)
     result = OpMayorIgual.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 123)
  def _reduce_41(val, _values, result)
     result = OpMayor.new(val[0], val[1], val[2]) 
    result
  end
.,.,

# reduce 42 omitted

# reduce 43 omitted

module_eval(<<'.,.,', 'parserGusb2.y', 134)
  def _reduce_44(val, _values, result)
    result = ArrayConsult.new(val[0],val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 135)
  def _reduce_45(val, _values, result)
    result = ArrayAsig.new(val[0],val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 139)
  def _reduce_46(val, _values, result)
    result = ListArrayAsig.new(nil,val[1],val[3],val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 140)
  def _reduce_47(val, _values, result)
    result = ListArrayAsig.new(nil,val[1],val[3],nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 144)
  def _reduce_48(val, _values, result)
     result = LiteralNumerico.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 149)
  def _reduce_49(val, _values, result)
     result = LiteralBooleano.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 150)
  def _reduce_50(val, _values, result)
     result = LiteralBooleano.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 155)
  def _reduce_51(val, _values, result)
     result = Instrucciones.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 156)
  def _reduce_52(val, _values, result)
     result = Instrucciones.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 162)
  def _reduce_53(val, _values, result)
     result = Instruccion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 163)
  def _reduce_54(val, _values, result)
     result = Instruccion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 164)
  def _reduce_55(val, _values, result)
     result = Instruccion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 165)
  def _reduce_56(val, _values, result)
     result = Instruccion.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 166)
  def _reduce_57(val, _values, result)
     result = Instruccion.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 167)
  def _reduce_58(val, _values, result)
     result = Instruccion.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 168)
  def _reduce_59(val, _values, result)
     result = Instruccion.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 173)
  def _reduce_60(val, _values, result)
     result = Entrada.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 178)
  def _reduce_61(val, _values, result)
     result = Salida.new(val[1], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 179)
  def _reduce_62(val, _values, result)
     result = Salida.new(val[1], "SALTO") 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 184)
  def _reduce_63(val, _values, result)
     result = Imprimir.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 185)
  def _reduce_64(val, _values, result)
     result = Imprimir.new(nil, val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 186)
  def _reduce_65(val, _values, result)
     result = Imprimir.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 187)
  def _reduce_66(val, _values, result)
     result = Imprimir.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 192)
  def _reduce_67(val, _values, result)
     result = Str.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 197)
  def _reduce_68(val, _values, result)
     result = Condicional.new(val[0],val[2],val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 198)
  def _reduce_69(val, _values, result)
     result = Condicional.new(val[0],val[2],nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 203)
  def _reduce_70(val, _values, result)
    result = Guardia.new(val[1],val[3],val[4])
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 204)
  def _reduce_71(val, _values, result)
    result = Guardia.new(val[1],val[3],nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 207)
  def _reduce_72(val, _values, result)
     result = IteradorFor.new(val[1], val[3], val[5], val[8]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 212)
  def _reduce_73(val, _values, result)
     result = IteratorDo.new(val[0],val[2],nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'parserGusb2.y', 213)
  def _reduce_74(val, _values, result)
     result = IteratorDo.new(val[0],val[2],val[3]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ParserGusb
